language: python
python:
  - "3.5.2"
cache: pip
install:
  - pip install -r ./requirements.txt
script:
  - pytest -v --cov=./ tests/
  - make
  - make dewarping_lib
  - make clean
  - make clean_dewarping_lib